### ISSUE TITLE
esx society 

### ISSUE THREAD

**Issue by jrence** [esx-framework/esx-legacy#13]
problem is.. 

reproduce the problem : when you set job boss on ambulance and other boss and employee list  see each other every department .... is not seperated each society like mechanic , police , ambulance

**Comment by jrence** [comment]
git tag <bug>

**Comment by thelindat** [comment]
If you updated to Legacy over a month ago, but have a more recent version of society, that might cause that to occur (couldn't say for certain); definitely not happening on my test server.

https://github.com/esx-framework/esx-legacy/blame/e2d86a242cc9ab0a68e154fbaba783ee2c71d79a/%5Besx%5D/es_extended/server/functions.lua#L252
That function was added in Legacy but modified a couple of times since, notably allowing arguments to limit the data returned.
