### ISSUE TITLE
none of the commands are working

### ISSUE THREAD

**Issue by Crispyrox** [esx-framework/esx-legacy#24]
It tells me to refer to their main.lua or function.lua. Am I missing something?

**Comment by x0Z3ro0x** [comment]
Post the errors instead of playing the telephone game. Chances are the ESX commands are conflicting with another resource with the same commands. This will cause neither to work.

I can confirm that a blank install of this Github does have working commands. Very little doesn't work with this repo when properly installed. I'd be happy to try and help you in the meantime.
