### ISSUE TITLE
merged esx_status and esx stress to es_extended

### ISSUE THREAD

**Issue by Mesrine67** [esx-framework/esx-legacy#410]
why not integrate the esx_status and esx stress into the es_extended? it would be much better seen it depends on the player
in exchange I can create a life hud, armor, food, for free

**Comment by ArkSeyonet** [comment]
It's possible, but the problem with moving functionality around is that people get upset about resources being given breaking changes.

**Comment by Mycroft-Studios** [comment]
esx stress also an official resource

**Comment by Mesrine67** [comment]
Configure the esx_status with a config. UseESXstatus = true or false
I do them for my secondary job system
seeing that esx stress and a resource that belongs to another person you can not integrate it ?

**Comment by Benzo00** [comment]
this is something we internally have to discuss but from my point of view its not going to happen atm, mainly of the reasons ark mentioned

**Comment by Mesrine67** [comment]
it's a shame I would have contributed to make a complete hud

**Comment by ArkSeyonet** [comment]
We've tried things like this before, and it has ended poorly. Just a reality that we cannot move functionality around that drastically. At least not without a pretty large portion of the userbase agreeing with it. It would be like shooting yourself in the foot, if you take functionality that has always been there and people have written scripts around it, to turn around and break functionality for all of those resources, because someone on the Github wanted to integrate it into es_extended.
