### ISSUE TITLE
[Bug] - es_extended - spawns vehicle without properties for shitty PC users

### ISSUE THREAD

**Issue by xrtw** [esx-framework/esx-legacy#429]
Hello, networked cars spawns without properties sometimes for players who has low PC

> ESX.Game.SpawnVehicle(vehicle.model, this_Garage.Spawner, this_Garage.Heading, function(callback_vehicle)
> 	ESX.Game.SetVehicleProperties(callback_vehicle, vehicle)
> 	TaskWarpPedIntoVehicle(PlayerPedId(), callback_vehicle, -1)
> end)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/188179884-4a384110-6af8-4bde-a976-2520e609c451.png)

For some reason server-side spawning (either the `CreateVehicle` RPC or `CREATE_AUTOMOBILE`) is now default.
It tries to use `NetworkRequestControlOfEntity` which _should not_ be used, can easily fail, and doesn't guarantee you'll keep ownership.

Server-side spawning requires properties to be set with statebags.

**Comment by applesignal** [comment]
The same problem encountered, if the vehicle is generated through ESX.Game.SpawnVehicle, the Properties cannot be set.

**Comment by iSentrie** [comment]
this:
https://github.com/esx-framework/esx-legacy/commit/b6241e194c1abb431aa17f8fb462f7ff16a8f210
brings even more problems, especially for shitty pc's, or streamed vehicles, example police job, you can spawn few vehicles until it's still loading in

**Comment by mahanmoulaei** [comment]
What if SetVehicleHasBeenOwnedByPlayer(vehicle, true) gets called before the [loop](https://github.com/esx-framework/esx-legacy/commit/b6241e194c1abb431aa17f8fb462f7ff16a8f210#diff-7c5fe49eaed2b038fa703507686eb885dc53c1f53a2c4287292a02a9b8ba9103R515) and NetworkRequestControlOfEntity(vehicle) gets called inside of the [loop](https://github.com/esx-framework/esx-legacy/commit/b6241e194c1abb431aa17f8fb462f7ff16a8f210#diff-7c5fe49eaed2b038fa703507686eb885dc53c1f53a2c4287292a02a9b8ba9103R515) as well? Does that help? I can't test this myself since I don't have a live server with players in it...

**Comment by iSentrie** [comment]
> What if SetVehicleHasBeenOwnedByPlayer(vehicle, true) gets called before the [loop](https://github.com/esx-framework/esx-legacy/commit/b6241e194c1abb431aa17f8fb462f7ff16a8f210#diff-7c5fe49eaed2b038fa703507686eb885dc53c1f53a2c4287292a02a9b8ba9103R515) and NetworkRequestControlOfEntity(vehicle) gets called inside of the [loop](https://github.com/esx-framework/esx-legacy/commit/b6241e194c1abb431aa17f8fb462f7ff16a8f210#diff-7c5fe49eaed2b038fa703507686eb885dc53c1f53a2c4287292a02a9b8ba9103R515) as well? Does that help? I can't test this myself since I don't have a live server with players in it...
> 
> Moreover, a better result can be obtained by increasing both Tries check from 250 to 10000.

you can test locally using -cl 2 in properties and running 2 clients at the same time
