### ISSUE TITLE
User group can use admin commands and Server Give Admin For User First Join Server

### ISSUE THREAD

**Issue by tonnizi** [esx-framework/esx-legacy#53]
So I have a problem like this that when I join the server for the first time I get directly to the admin group and many others get it too.
The user group can also use admin commands

**Comment by timonation** [comment]
i have the same issue

**Comment by x0Z3ro0x** [comment]
Can you provide anymore details than, "something isn't working"?

More information helps developers and others find where and what the issue is. As it stands, the latest version as of writing this does NOT contain the bug you are talking about. All my testers have been logged as users. I am the only admin to be auto promoted and that is thanks to my perms.cfg

I am happy to try and help if you can give more information.

**Comment by Luke20201** [comment]
@tonnizi @timonation 

Hi, I'm sorry you're experiencing this issue with your servers.

By default, player's receive the **user** group. The only way this should change, is when you edit the default value of the group in the database. 
Please ensure that this is set to **user**

As for regular user's being able to use command's, this is most likely an edit you made yourself.
[Here, you will see the permission's required to use each command](https://github.com/esx-framework/esx-legacy/blob/main/%5Besx%5D/es_extended/server/commands.lua)

If neither solution works, please reply to me!
