### ISSUE TITLE
I need help am getting an error with es_extended

### ISSUE THREAD

**Issue by ligmabalzzzzz** [esx-framework/esx-legacy#55]
Help I get this error 

```
[script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:7: attempt to index a nil value (global 'Config')

[script:es_extended] SCRIPT ERROR: @es_extended/server/paycheck.lua:4: attempt to index a nil value (global 'Config')
```

**Comment by Luke20201** [comment]
Hey,

This issue is commonly experienced when there is some form of Syntax error in the Config file. 
I recommened you reinstall the Config file, and edit it according to the Syntax is display's. 
For more information, you should see an error in the console when you join, telling you where-about's the Syntax error is!
